import type { Metadata } from "next";

import DarkVeil from "@/components/ui/DarkVeil";

import Header from "@/components/layout/Header/Header";
import "@/styles/global.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="relative h-150 w-full">
      <DarkVeil speed={1} />
      <Header />
      {children}
    </main>
  );
}
