import type { Metadata } from "next";

import DarkVeil from "@/components/ui/DarkVeil";

import Header from "@/components/layout/Header/Header";
import "./globals.css";

import { Rubik } from "next/font/google";

const rubik = Rubik({
  variable: "--rubik",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${rubik.variable} antialiased`}>
        <main className="relative h-150 w-full">
          <DarkVeil speed={1} />
          <Header />
        </main>
        {children}
      </body>
    </html>
  );
}
