import type { Metadata } from "next";

import "@/styles/global.css";

import { Rubik } from "next/font/google";

const rubik = Rubik({
  variable: "--rubik",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <main>{children}</main>;
}
